import Head from "next/head";

export default function About() {
  return (
    <>
      <Head>
        <title>Tonemate 서비스 소개</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>서비스 소개</div>
      </main>
    </>
  );
}
