import Head from "next/head";
import { useEffect } from "react";
import Layout from "@/components/layout";
import LandingContainer from "@/components/content/lading-container";
import Intro from "@/components/about/intro";

export default function About() {
  useEffect(() => {
    const handleWheel = (e) => {
      e.preventDefault();
    };
    window.addEventListener("wheel", handleWheel, { passive: false });
    return () => {
      window.removeEventListener("wheel", handleWheel);
    };
  }, []);
  var scroll = function (e) {
    // 스크롤 방향에 따라 이동 거리 계산
    const delta = e.deltaY > 0 ? window.innerHeight : -window.innerHeight;
    // 현재 스크롤 위치에 이동 거리 더하기
    window.scrollBy({
      top: delta,
      behavior: "smooth",
    });
  };

  var title = [
    "자신에게 어울리는 노래를 찾아보세요",
    "녹음 한번으로 분석을",
    "5000곡 그리고 100명",
  ];
  var content = [
    "ToneMate는 유저의 음색과 비슷한 가수를 찾아줍니다.",
    "한 번만 녹음하세요. ToneMate가 당신의 목소리를 분석해드려요.",
    "ToneMate가 맞춤 서비스를 제공하기 위해 분석한 데이터에요.",
  ];

  return (
    <>
      <Head name="이상현">
        <title>Tonemate 서비스 소개</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="scrollbar" onWheel={scroll}>
        <Intro index={0} title={title[0]} content={content[0]} />
        <Intro index={1} title={title[1]} content={content[1]} />
        <Intro index={2} title={title[2]} content={content[2]} />
      </main>
    </>
  );
}
