import Head from "next/head";
import NavBarMobile from "@/components/navigation/nav-bar-mobile";
import NavBarDesk from "@/components/navigation/nav-bar-desk";

export default function HomePage() {
  return (
    <>
      <Head>
        <title>Tonemate</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="md:flex sm:block w-screen h-screen">
        <NavBarMobile />
        <NavBarDesk />
        <div className="block md:w-5/6 sm:w-full h-full bg-black"></div>
      </main>
    </>
  );
}
