import Head from "next/head";
import Layout from "@/components/layout";
import HalfContainer from "@/components/content/half-container";

export default function HomePage() {
  return (
    <>
      <Head>
        <title>Tonemate</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Layout>
          <HalfContainer>
            <div className="flex w-140 h-full bg-gray-400"></div>
            <div className="flex flex-col grow justify-center items-start bg-gray-200">
              <div className="m-3">
                <p className="text-white">TONEMATE</p>
              </div>
            </div>
          </HalfContainer>
          <HalfContainer>
            <div className="flex flex-row m-3">
              <p className="text-2xl text-white">TONEMATE 서비스 바로가기 </p>
            </div>
          </HalfContainer>
        </Layout>
      </main>
    </>
  );
}
