import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export default function LandingPage() {
  return (
    <>
      <Head>
        <title>Tonemate</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="flex p-0 m-0 w-full h-screen bg-black"></div>
      </main>
    </>
  );
}
