import Head from "next/head";
import Layout from "@/components/layout";

export default function MyPage() {
  return (
    <>
      <Head>
        <title>마이페이지</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main></main>
    </>
  );
}
