import Head from "next/head";
import Layout from "@/components/layout";
import SearchComponent from "@/components/main/search-component";

export default function Search() {
  return (
    <>
      <Head>
        <title>TONEMATE - 노래 검색</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Layout>
          <div className="flex flex-col justify-center items-center w-full h-1/6 bg-white">
            검색 엔진
          </div>
          <div className="flex flex-col justify-center items-center w-full h-4/6 bg-white">
            테이블
          </div>
          {/* <SearchComponent />
          <div>
            <table className="table w-full">
              <thead>
                <tr>
                  <th>번호</th>
                  <th>노래</th>
                  <th>가수</th>
                  <th>TJ</th>
                  <th>KY</th>
                  <th>좋아요</th>
                </tr>
              </thead>
              <tbody></tbody>
            </table>
          </div> */}
        </Layout>
      </main>
    </>
  );
}
