import Head from "next/head";
import Layout from "@/components/layout";
import HalfContainer from "@/components/content/half-container";

export default function Search() {
  const items = [];

  return (
    <>
      <Head>
        <title>TONEMATE - 노래 검색</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Layout>
          <div>
            <select className="select w-full max-w-xs">
              <option disabled selected>
                검색 분류
              </option>
              <option>가수</option>
              <option>노래</option>
              <option>Bart</option>
              <option>Lisa</option>
              <option>Maggie</option>
            </select>
          </div>
          <div>
            <table className="table w-full">
              <thead>
                <tr>
                  <th>번호</th>
                  <th>노래</th>
                  <th>가수</th>
                  <th>TJ</th>
                  <th>KY</th>
                  <th>좋아요</th>
                </tr>
              </thead>
              <tbody></tbody>
            </table>
          </div>
        </Layout>
      </main>
    </>
  );
}
