import Head from "next/head";
import Layout from "@/components/layout";
import HalfContainer from "@/components/content/half-container";

export default function MusicList() {
  return (
    <>
      <Head>
        <title>애창곡 리스트</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Layout>
          <div className="flex flex-col justify-center items-center w-full h-1/6 bg-white">
            검색 엔진
          </div>
          <div className="flex flex-col justify-center items-center w-full h-4/6 bg-white">
            테이블
          </div>
        </Layout>
      </main>
    </>
  );
}
