import Head from "next/head";

export default function VocalColor() {
  return (
    <>
      <Head>
        <title>음색검사</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="block w-11/12">
        <p className="text-white">음색 검사</p>
      </div>
    </>
  );
}
