import Head from "next/head";
import Layout from "@/components/layout";
import HalfContainer from "@/components/content/half-container";

export default function VocalRange() {
  return (
    <>
      <Head>
        <title>음역대검사</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Layout>
          <div className="flex w-full h-1/4 bg-white"></div>
          <div className="flex w-full h-1/4 bg-white"></div>
          <div className="flex w-full h-1/4 bg-white"></div>
        </Layout>
      </main>
    </>
  );
}
